#!/usr/bin/env python3
"""Analyze per-fold residuals for DataFlash prediction CSV files."""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from pathlib import Path


AXES = [
    ("east", "true_dx_east_m", "pred_dx_east_m"),
    ("north", "true_dy_north_m", "pred_dy_north_m"),
    ("up", "true_dz_up_m", "pred_dz_up_m"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pred-csv",
        type=Path,
        default=Path("derived/predictions/dataflash_sequence_fixed100_bias/imu_att_h5000_l5000_s20/sequence_ridge_pred.csv"),
    )
    parser.add_argument(
        "--bias-csv",
        type=Path,
        default=Path("derived/predictions/dataflash_sequence_fixed100_bias/imu_att_h5000_l5000_s20/sequence_ridge_bias_corrected_pred.csv"),
    )
    parser.add_argument("--report", type=Path, default=Path("reports/experiments/dataflash_fold_residuals_sequence_fixed100.md"))
    return parser.parse_args()


def as_float(value: str) -> float:
    try:
        return float(value)
    except ValueError:
        return math.nan


def read_by_fold(path: Path) -> dict[str, list[dict[str, str]]]:
    folds: dict[str, list[dict[str, str]]] = defaultdict(list)
    with path.open(newline="", encoding="utf-8") as file:
        for row in csv.DictReader(file):
            folds[row.get("fold_id", "1")].append(row)
    return dict(folds)


def mean(values: list[float]) -> float:
    return sum(values) / max(len(values), 1)


def p95(values: list[float]) -> float:
    if not values:
        return math.nan
    ordered = sorted(values)
    return ordered[int(0.95 * (len(ordered) - 1))]


def summarize(rows: list[dict[str, str]]) -> dict[str, float]:
    result: dict[str, float] = {"count": float(len(rows))}
    errors_3d: list[float] = []
    target_norms: list[float] = []
    pred_norms: list[float] = []
    for row in rows:
        err_sq = 0.0
        target_sq = 0.0
        pred_sq = 0.0
        for axis, true_col, pred_col in AXES:
            true = as_float(row[true_col])
            pred = as_float(row[pred_col])
            residual = true - pred
            result.setdefault(f"residual_{axis}_sum", 0.0)
            result[f"residual_{axis}_sum"] += residual
            err_sq += residual * residual
            target_sq += true * true
            pred_sq += pred * pred
        errors_3d.append(math.sqrt(err_sq))
        target_norms.append(math.sqrt(target_sq))
        pred_norms.append(math.sqrt(pred_sq))
    for axis, _, _ in AXES:
        result[f"residual_{axis}_mean"] = result.pop(f"residual_{axis}_sum", 0.0) / max(len(rows), 1)
    result["mae_3d"] = mean(errors_3d)
    result["p95_3d"] = p95(errors_3d)
    result["target_norm_mean"] = mean(target_norms)
    result["pred_norm_mean"] = mean(pred_norms)
    return result


def row_line(label: str, fold: str, values: dict[str, float]) -> str:
    return (
        f"| `{label}` | {fold} | {values['count']:.0f} | {values['mae_3d']:.3f} | {values['p95_3d']:.3f} | "
        f"{values['target_norm_mean']:.3f} | {values['pred_norm_mean']:.3f} | "
        f"{values['residual_east_mean']:.3f} | {values['residual_north_mean']:.3f} | {values['residual_up_mean']:.3f} |"
    )


def write_report(path: Path, pred_csv: Path, bias_csv: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    raw = read_by_fold(pred_csv)
    bias = read_by_fold(bias_csv)
    lines = [
        "# DataFlash Fold Residuals",
        "",
        "This report is generated by `src/analyze_dataflash_fold_residuals.py`.",
        "",
        f"Raw predictions: `{pred_csv}`",
        f"Bias-corrected predictions: `{bias_csv}`",
        "",
        "Residual is `true_delta - predicted_delta`; positive residual means the model under-predicts that axis.",
        "",
        "| model | fold | rows | MAE 3D | P95 3D | target norm mean | pred norm mean | mean residual east | mean residual north | mean residual up |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for fold in sorted(raw, key=int):
        lines.append(row_line("sequence_ridge", fold, summarize(raw[fold])))
        lines.append(row_line("sequence_ridge_bias_corrected", fold, summarize(bias[fold])))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    write_report(args.report, args.pred_csv, args.bias_csv)
    print(f"Wrote {args.report}")


if __name__ == "__main__":
    main()
