#!/usr/bin/env python3
"""Build sparse non-overlapping rollout diagnostics from DataFlash predictions."""

from __future__ import annotations

import argparse
import csv
import json
import math
from collections import defaultdict
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--pred-csv",
        type=Path,
        default=Path("derived/predictions/dataflash_rolling_validation/imu_att_h5000_l5000/ridge_pred.csv"),
    )
    parser.add_argument("--report", type=Path, default=Path("reports/experiments/dataflash_rollout_imu_att_h5000.md"))
    parser.add_argument("--rollout-csv", type=Path, default=Path("derived/predictions/dataflash_rollout/imu_att_h5000_l5000_rollout.csv"))
    parser.add_argument("--html", type=Path, default=Path("artifacts/generated/dataflash_rollout/index.html"))
    return parser.parse_args()


def as_float(value: str) -> float:
    try:
        return float(value)
    except ValueError:
        return math.nan


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def select_non_overlapping(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    selected: list[dict[str, str]] = []
    next_time = -math.inf
    for row in sorted(rows, key=lambda item: as_float(item["time_s"])):
        time_s = as_float(row["time_s"])
        if time_s + 1e-9 < next_time:
            continue
        selected.append(row)
        next_time = as_float(row["future_time_s"])
    return selected


def build_rollout(rows: list[dict[str, str]]) -> list[dict[str, float | str]]:
    if not rows:
        return []
    selected = select_non_overlapping(rows)
    start = selected[0]
    pred_e = as_float(start["current_east_m"])
    pred_n = as_float(start["current_north_m"])
    pred_u = as_float(start["current_up_m"])
    result: list[dict[str, float | str]] = []
    for step_idx, row in enumerate(selected, start=1):
        pred_e += as_float(row["pred_dx_east_m"])
        pred_n += as_float(row["pred_dy_north_m"])
        pred_u += as_float(row["pred_dz_up_m"])
        true_e = as_float(row["true_future_east_m"])
        true_n = as_float(row["true_future_north_m"])
        true_u = as_float(row["true_future_up_m"])
        err_e = pred_e - true_e
        err_n = pred_n - true_n
        err_u = pred_u - true_u
        err_3d = math.sqrt(err_e * err_e + err_n * err_n + err_u * err_u)
        result.append(
            {
                "fold_id": row.get("fold_id", "1"),
                "step": step_idx,
                "time_s": as_float(row["future_time_s"]),
                "true_east_m": true_e,
                "true_north_m": true_n,
                "true_up_m": true_u,
                "pred_east_m": pred_e,
                "pred_north_m": pred_n,
                "pred_up_m": pred_u,
                "err_east_m": err_e,
                "err_north_m": err_n,
                "err_up_m": err_u,
                "err_3d_m": err_3d,
            }
        )
    return result


def metrics(rows: list[dict[str, float | str]]) -> dict[str, float]:
    errors = [float(row["err_3d_m"]) for row in rows]
    if not errors:
        return {"steps": 0.0, "final_error_m": math.nan, "mean_error_m": math.nan, "max_error_m": math.nan}
    return {
        "steps": float(len(errors)),
        "final_error_m": errors[-1],
        "mean_error_m": sum(errors) / len(errors),
        "max_error_m": max(errors),
    }


def write_rollout_csv(path: Path, rows: list[dict[str, float | str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "fold_id",
        "step",
        "time_s",
        "true_east_m",
        "true_north_m",
        "true_up_m",
        "pred_east_m",
        "pred_north_m",
        "pred_up_m",
        "err_east_m",
        "err_north_m",
        "err_up_m",
        "err_3d_m",
    ]
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({name: format_value(row[name]) for name in fieldnames})


def format_value(value: float | str) -> str:
    if isinstance(value, float):
        return f"{value:.6f}"
    return str(value)


def write_report(path: Path, pred_csv: Path, rollout_csv: Path, html: Path, by_fold: dict[str, list[dict[str, float | str]]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    all_rows = [row for rows in by_fold.values() for row in rows]
    lines = [
        "# DataFlash Sparse Rollout",
        "",
        "This report is generated by `src/build_dataflash_rollout.py`.",
        "",
        f"Source predictions: `{pred_csv}`",
        f"Rollout CSV: `{rollout_csv}`",
        f"HTML: `{html}`",
        "",
        "Method: within each rolling-validation fold, use non-overlapping prediction rows only. Start from the true current POS at the first selected row, then accumulate predicted 5-second displacement vectors.",
        "",
        "This is a sparse displacement rollout, not a full inertial navigation integration at IMU rate.",
        "",
        "## Metrics",
        "",
        "| fold | steps | final error m | mean error m | max error m |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for fold_id, rows in sorted(by_fold.items(), key=lambda item: int(item[0])):
        values = metrics(rows)
        lines.append(
            f"| {fold_id} | {values['steps']:.0f} | {values['final_error_m']:.3f} | "
            f"{values['mean_error_m']:.3f} | {values['max_error_m']:.3f} |"
        )
    values = metrics(all_rows)
    lines.append(
        f"| all | {values['steps']:.0f} | {values['final_error_m']:.3f} | "
        f"{values['mean_error_m']:.3f} | {values['max_error_m']:.3f} |"
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def html_template(by_fold: dict[str, list[dict[str, float | str]]]) -> str:
    payload = json.dumps(by_fold, ensure_ascii=True)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DataFlash Sparse Rollout</title>
  <style>
    :root {{
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: #f5f6f8;
      color: #18212f;
    }}
    body {{
      margin: 0;
      min-height: 100vh;
      display: grid;
      grid-template-rows: auto 1fr;
    }}
    header {{
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 14px;
      padding: 14px 18px;
      background: #ffffff;
      border-bottom: 1px solid #d8dde5;
    }}
    h1 {{
      margin: 0;
      font-size: 18px;
      letter-spacing: 0;
    }}
    select {{
      font: inherit;
      padding: 7px 9px;
      min-width: 180px;
      border: 1px solid #bac3cf;
      border-radius: 6px;
      background: #ffffff;
      color: #18212f;
    }}
    main {{
      display: grid;
      grid-template-columns: minmax(0, 1fr) 280px;
      min-height: 0;
    }}
    svg {{
      width: 100%;
      height: calc(100vh - 62px);
      background: #eef1f5;
    }}
    aside {{
      padding: 16px;
      border-left: 1px solid #d8dde5;
      background: #ffffff;
    }}
    .metric {{
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 8px;
      padding: 8px 0;
      border-bottom: 1px solid #edf0f4;
      font-size: 14px;
    }}
    .legend {{
      display: grid;
      gap: 8px;
      margin-top: 16px;
      font-size: 14px;
    }}
    .key {{
      display: flex;
      gap: 8px;
      align-items: center;
    }}
    .swatch {{
      width: 22px;
      height: 4px;
      border-radius: 2px;
    }}
    @media (max-width: 820px) {{
      header {{ flex-direction: column; align-items: stretch; }}
      main {{ grid-template-columns: 1fr; }}
      svg {{ height: 68vh; }}
      aside {{ border-left: 0; border-top: 1px solid #d8dde5; }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>DataFlash Sparse Rollout</h1>
    <select id="foldSelect" aria-label="Fold"></select>
  </header>
  <main>
    <svg id="plot" role="img" aria-label="Sparse rollout plot"></svg>
    <aside>
      <div class="metric"><span>Steps</span><strong id="steps">-</strong></div>
      <div class="metric"><span>Final Error</span><strong id="final">-</strong></div>
      <div class="metric"><span>Mean Error</span><strong id="mean">-</strong></div>
      <div class="metric"><span>Max Error</span><strong id="max">-</strong></div>
      <div class="legend">
        <div class="key"><span class="swatch" style="background:#2563eb"></span><span>true future POS</span></div>
        <div class="key"><span class="swatch" style="background:#dc2626"></span><span>accumulated predicted POS</span></div>
      </div>
    </aside>
  </main>
  <script>
    const folds = {payload};
    const select = document.getElementById('foldSelect');
    const svg = document.getElementById('plot');
    for (const foldId of Object.keys(folds).sort((a, b) => Number(a) - Number(b))) {{
      const option = document.createElement('option');
      option.value = foldId;
      option.textContent = `Fold ${{foldId}}`;
      select.appendChild(option);
    }}
    function pathFor(points, xKey, yKey, scale) {{
      return points.map((p, i) => `${{i ? 'L' : 'M'}} ${{scale.x(p[xKey]).toFixed(2)}} ${{scale.y(p[yKey]).toFixed(2)}}`).join(' ');
    }}
    function stats(rows) {{
      const errors = rows.map((row) => row.err_3d_m);
      return {{
        steps: rows.length,
        final: errors[errors.length - 1] || 0,
        mean: errors.reduce((a, b) => a + b, 0) / Math.max(errors.length, 1),
        max: Math.max(...errors, 0),
      }};
    }}
    function render() {{
      const rows = folds[select.value] || [];
      const xs = rows.flatMap((p) => [p.true_east_m, p.pred_east_m]);
      const ys = rows.flatMap((p) => [p.true_north_m, p.pred_north_m]);
      const minX = Math.min(...xs);
      const maxX = Math.max(...xs);
      const minY = Math.min(...ys);
      const maxY = Math.max(...ys);
      const pad = 34;
      const rect = svg.getBoundingClientRect();
      const w = Math.max(rect.width, 320);
      const h = Math.max(rect.height, 320);
      const spanX = Math.max(maxX - minX, 1);
      const spanY = Math.max(maxY - minY, 1);
      const scale = {{
        x: (x) => pad + (x - minX) / spanX * (w - pad * 2),
        y: (y) => h - pad - (y - minY) / spanY * (h - pad * 2),
      }};
      svg.setAttribute('viewBox', `0 0 ${{w}} ${{h}}`);
      svg.innerHTML = `
        <path d="${{pathFor(rows, 'true_east_m', 'true_north_m', scale)}}" fill="none" stroke="#2563eb" stroke-width="2.6"/>
        <path d="${{pathFor(rows, 'pred_east_m', 'pred_north_m', scale)}}" fill="none" stroke="#dc2626" stroke-width="2.6"/>
      `;
      const s = stats(rows);
      document.getElementById('steps').textContent = s.steps.toLocaleString();
      document.getElementById('final').textContent = `${{s.final.toFixed(3)}} m`;
      document.getElementById('mean').textContent = `${{s.mean.toFixed(3)}} m`;
      document.getElementById('max').textContent = `${{s.max.toFixed(3)}} m`;
    }}
    select.addEventListener('change', render);
    window.addEventListener('resize', render);
    render();
  </script>
</body>
</html>
"""


def write_html(path: Path, by_fold: dict[str, list[dict[str, float | str]]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html_template(by_fold), encoding="utf-8")


def main() -> None:
    args = parse_args()
    source_rows = read_rows(args.pred_csv)
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in source_rows:
        grouped[row.get("fold_id", "1")].append(row)

    by_fold = {fold_id: build_rollout(rows) for fold_id, rows in grouped.items()}
    all_rollout_rows = [row for rows in by_fold.values() for row in rows]
    write_rollout_csv(args.rollout_csv, all_rollout_rows)
    write_report(args.report, args.pred_csv, args.rollout_csv, args.html, by_fold)
    write_html(args.html, by_fold)
    print(f"Wrote {args.report}")
    print(f"Wrote {args.rollout_csv}")
    print(f"Wrote {args.html}")


if __name__ == "__main__":
    main()
