#!/usr/bin/env python3
"""Run chronological within-flight debug baselines on window datasets."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from run_window_baselines import ALPHAS, Dataset, fit_ridge, metrics, predict_ridge, read_dataset


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--datasets",
        nargs="*",
        type=Path,
        default=sorted(
            path
            for path in Path("derived/datasets").glob("windows_module_h*_l*.npz")
            if "_trim" not in path.stem
        ),
    )
    parser.add_argument("--report", type=Path, default=Path("reports/experiments/module_window_chronological_debug.md"))
    parser.add_argument("--train-frac", type=float, default=0.6)
    parser.add_argument("--val-frac", type=float, default=0.2)
    return parser.parse_args()


def chronological_masks(dataset: Dataset, train_frac: float, val_frac: float) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    train = np.zeros(len(dataset.y), dtype=bool)
    val = np.zeros(len(dataset.y), dtype=bool)
    test = np.zeros(len(dataset.y), dtype=bool)
    for flight in sorted(set(dataset.flight_id.tolist())):
        indices = np.nonzero(dataset.flight_id == flight)[0]
        order = indices[np.argsort(dataset.time_s[indices])]
        train_end = max(1, int(len(order) * train_frac))
        val_end = max(train_end + 1, int(len(order) * (train_frac + val_frac)))
        val_end = min(val_end, len(order) - 1)
        train[order[:train_end]] = True
        val[order[train_end:val_end]] = True
        test[order[val_end:]] = True
    return train, val, test


def choose_ridge(dataset: Dataset, train_mask: np.ndarray, val_mask: np.ndarray) -> tuple[float, tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]]:
    best_alpha = ALPHAS[0]
    best_params = fit_ridge(dataset.x[train_mask], dataset.y[train_mask], best_alpha)
    best_score = float("inf")
    for alpha in ALPHAS:
        params = fit_ridge(dataset.x[train_mask], dataset.y[train_mask], alpha)
        pred = predict_ridge(dataset.x[val_mask], params)
        score = float(metrics(dataset.y[val_mask], pred)["mae_3d"])
        if score < best_score:
            best_score = score
            best_alpha = alpha
            best_params = params
    return best_alpha, best_params


def metric_row(dataset: str, subset: str, model: str, alpha: float | None, values: dict[str, float | list[float]]) -> str:
    mae = values["mae_axis"]
    rmse = values["rmse_axis"]
    assert isinstance(mae, list)
    assert isinstance(rmse, list)
    alpha_text = "" if alpha is None else f"{alpha:g}"
    return (
        f"| `{dataset}` | `{subset}` | `{model}` | {alpha_text} | "
        f"{mae[0]:.3f} | {mae[1]:.3f} | {mae[2]:.3f} | {values['mae_3d']:.3f} | "
        f"{rmse[0]:.3f} | {rmse[1]:.3f} | {rmse[2]:.3f} | {values['rmse_3d']:.3f} | {values['p95_3d']:.3f} |"
    )


def write_report(path: Path, rows: list[str], notes: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Module Window Chronological Debug",
        "",
        "This report is generated by `src/run_chronological_debug.py`.",
        "",
        "This is not the main evaluation. It intentionally trains and tests within the same flights to check whether the feature set has any learnable signal before testing transfer to new flights.",
        "",
        "| dataset | subset | model | alpha | MAE east | MAE north | MAE up | MAE 3D | RMSE east | RMSE north | RMSE up | RMSE 3D | P95 3D |",
        "| --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    lines.extend(rows)
    lines.extend(["", "## Split Details", ""])
    lines.extend(f"- {note}" for note in notes)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows: list[str] = []
    notes: list[str] = []
    for path in args.datasets:
        dataset = read_dataset(path)
        train_mask, val_mask, test_mask = chronological_masks(dataset, args.train_frac, args.val_frac)
        best_alpha, params = choose_ridge(dataset, train_mask, val_mask)
        y_train = dataset.y[train_mask]
        for subset_name, mask in [("val", val_mask), ("test", test_mask)]:
            y_true = dataset.y[mask]
            predictions = {
                "zero": np.zeros_like(y_true),
                "train_mean": np.repeat(y_train.mean(axis=0)[None, :], len(y_true), axis=0),
                "ridge": predict_ridge(dataset.x[mask], params),
            }
            for model_name, pred in predictions.items():
                rows.append(
                    metric_row(
                        dataset.name,
                        subset_name,
                        model_name,
                        best_alpha if model_name == "ridge" else None,
                        metrics(y_true, pred),
                    )
                )
        notes.append(
            f"`{dataset.name}` train={int(train_mask.sum())} val={int(val_mask.sum())} test={int(test_mask.sum())} best_alpha={best_alpha:g}"
        )
        print(f"Ran {dataset.name}")
    write_report(args.report, rows, notes)
    print(f"Wrote {args.report}")


if __name__ == "__main__":
    main()
